CREATE TABLE CURRENCY
   (	"CODE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"EXCHANGERATE" NUMBER(10,5), 
	 CONSTRAINT "CURRENCY_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) 
   
   ALTER TABLE PLACEMENT 
ADD (
    CURRENCY VARCHAR2(5),
    AMOUNT_IN_BAM NUMBER(30,5)
);

ALTER TABLE HRORGANIZATION 
ADD (
    EMAIL VARCHAR2(100)
);