spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@exa1-sca:1521:exaubbt1
    username: CAP_UBB
    password: UBB_CAP
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true