spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: DEVELOPER
    password: admin
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true